app:
  name: guapin
  port: 8989

db:
  host:     127.0.0.1
  name:     guapin
  user:     root
  password: root
  port:     3306
  driver:   mysql
file:
  path: upload
wx:
  appid: wxa5b486c6b918ecfb
  appsecret: e04004829d4c383b4db7769d88dfbca1
